// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateOrJoinMatchReducer from "../create_or_join_match_reducer";
import LeaveMatchReducer from "../leave_match_reducer";
import PublishCombatOutcomeReducer from "../publish_combat_outcome_reducer";
import ResetMatchCombatReducer from "../reset_match_combat_reducer";
import UpdateSwordPoseReducer from "../update_sword_pose_reducer";
import UpsertCombatIntentReducer from "../upsert_combat_intent_reducer";

export type CreateOrJoinMatchParams = __Infer<typeof CreateOrJoinMatchReducer>;
export type LeaveMatchParams = __Infer<typeof LeaveMatchReducer>;
export type PublishCombatOutcomeParams = __Infer<typeof PublishCombatOutcomeReducer>;
export type ResetMatchCombatParams = __Infer<typeof ResetMatchCombatReducer>;
export type UpdateSwordPoseParams = __Infer<typeof UpdateSwordPoseReducer>;
export type UpsertCombatIntentParams = __Infer<typeof UpsertCombatIntentReducer>;

