// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomCode: __t.string().primaryKey().name("room_code"),
  seq: __t.u32(),
  kind: __t.string(),
  actorIdentity: __t.identity().name("actor_identity"),
  targetIdentity: __t.identity().name("target_identity"),
  playerRootX: __t.f32().name("player_root_x"),
  dummyRootX: __t.f32().name("dummy_root_x"),
  winnerIdentity: __t.option(__t.identity()).name("winner_identity"),
  updatedMs: __t.u64().name("updated_ms"),
});
