// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomCode: __t.string().name("room_code"),
  blocking: __t.bool(),
  slashSeq: __t.u32().name("slash_seq"),
  guardX: __t.f32().name("guard_x"),
  guardY: __t.f32().name("guard_y"),
  updatedMs: __t.u64().name("updated_ms"),
});
