// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomCode: __t.string().primaryKey().name("room_code"),
  seq: __t.u32(),
  phase: __t.string(),
  countdownLabel: __t.string().name("countdown_label"),
  roundIndex: __t.u32().name("round_index"),
  p1Wins: __t.u32().name("p1_wins"),
  p2Wins: __t.u32().name("p2_wins"),
  matchWinner: __t.string().name("match_winner"),
  playerRootX: __t.f32().name("player_root_x"),
  dummyRootX: __t.f32().name("dummy_root_x"),
  updatedMs: __t.u64().name("updated_ms"),
});
