// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  seq: __t.u32(),
  phase: __t.string(),
  countdownLabel: __t.string(),
  roundIndex: __t.u32(),
  p1Wins: __t.u32(),
  p2Wins: __t.u32(),
  matchWinner: __t.string(),
  playerRootX: __t.f32(),
  dummyRootX: __t.f32(),
};
