// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomCode: __t.string().name("room_code"),
  type: __t.string(),
  posX: __t.f32().name("pos_x"),
  posY: __t.f32().name("pos_y"),
  posZ: __t.f32().name("pos_z"),
  rotX: __t.f32().name("rot_x"),
  rotY: __t.f32().name("rot_y"),
  rotZ: __t.f32().name("rot_z"),
  rotW: __t.f32().name("rot_w"),
  sessionGeneration: __t.u32().name("session_generation"),
  sequence: __t.u32(),
  updatedMs: __t.u64().name("updated_ms"),
});
