// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CombatIntent = __t.object("CombatIntent", {
  identity: __t.identity(),
  roomCode: __t.string(),
  blocking: __t.bool(),
  slashSeq: __t.u32(),
  guardX: __t.f32(),
  guardY: __t.f32(),
  updatedMs: __t.u64(),
});
export type CombatIntent = __Infer<typeof CombatIntent>;

export const CombatOutcome = __t.object("CombatOutcome", {
  roomCode: __t.string(),
  seq: __t.u32(),
  kind: __t.string(),
  actorIdentity: __t.identity(),
  targetIdentity: __t.identity(),
  playerRootX: __t.f32(),
  dummyRootX: __t.f32(),
  winnerIdentity: __t.option(__t.identity()),
  updatedMs: __t.u64(),
});
export type CombatOutcome = __Infer<typeof CombatOutcome>;

export const Match = __t.object("Match", {
  roomCode: __t.string(),
  hostIdentity: __t.identity(),
  createdMs: __t.u64(),
});
export type Match = __Infer<typeof Match>;

export const MatchPlayer = __t.object("MatchPlayer", {
  identity: __t.identity(),
  roomCode: __t.string(),
  joinedMs: __t.u64(),
  ready: __t.bool(),
});
export type MatchPlayer = __Infer<typeof MatchPlayer>;

export const SwordPose = __t.object("SwordPose", {
  identity: __t.identity(),
  roomCode: __t.string(),
  type: __t.string(),
  posX: __t.f32(),
  posY: __t.f32(),
  posZ: __t.f32(),
  rotX: __t.f32(),
  rotY: __t.f32(),
  rotZ: __t.f32(),
  rotW: __t.f32(),
  sessionGeneration: __t.u32(),
  sequence: __t.u32(),
  updatedMs: __t.u64(),
});
export type SwordPose = __Infer<typeof SwordPose>;

